name: vcore
description: A starting point for Dart libraries or applications.
version: 0.0.1
#author: Your Name <email@example.com>
#homepage: https://www.example.com

dependencies:
  built_collection: "^1.0.0"
  built_json: "^0.0.5"
  built_value:
    path: ../built_value.dart/built_value
#  stuff: ">=0.0.4 <0.1.0"
dev_dependencies:
  test: ">=0.12.0 <0.13.0"
  built_json_generator: '^0.0.5'
  built_value_generator:
    path: ../built_value.dart/built_value_generator
environment:
  sdk: ">=1.15.0 <2.0.0"
